[package]
name = "pve-api-types"
# For the major part of the version we probably want to track the lowest PVE
# version we fully support. The minor part can be bumped if there are breaking
# changes in the crate and type API code here, and minor for all new things and
# fixes.
version = "8.1.2"
description = "Proxmox VE API types"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1"
regex.workspace = true
serde = { workspace = true, features = [ "derive" ] }
serde_json.workspace = true
serde_plain.workspace = true
#
proxmox-api-macro.workspace = true
proxmox-apt-api-types.workspace = true
proxmox-fixed-string.workspace = true
proxmox-serde = { workspace = true, features = [ "perl" ] }
proxmox-schema = { workspace = true, features = [ "api-types", "api-macro" ] }

# For the client feature:
percent-encoding = { workspace = true, optional = true }
proxmox-client = { version = "1", optional = true, features = ["perl-api-path-builder"] }

[features]
default = []
client-util = [ "dep:percent-encoding" ]
client = [ "client-util", "dep:proxmox-client" ]
