[package]
name = "proxmox-ldap"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
exclude.workspace = true
description = "Proxmox library for LDAP authentication/synchronization"

[dependencies]
anyhow.workspace = true
ldap3 = { workspace = true, default_features = false, features = ["tls"] }
serde = { workspace = true, features = ["derive"] }
native-tls.workspace = true

[dev_dependencies]
proxmox-async.workspace = true
