[package]
name = "proxmox-shared-memory"
version = "0.2.3"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared memory helpers and shared mutex implementation"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
nix.workspace = true

proxmox-sys.workspace = true
