[package]
name = "proxmox-section-config"
description = "proxmox schema based section config format parsing"
version = "3.1.0"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true

proxmox-schema.workspace = true
# FIXME: remove!
proxmox-lang.workspace = true

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
