[package]
name = "proxmox-sortable-macro"
version = "0.1.0"
authors = ["Wolfgang Bumiller <w.bumiller@proxmox.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
#failure = { version = "0.1", default-features = false, features = ["std"] }
failure = "0.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = [ "full", "visit-mut" ] }
