[package]
name = "proxmox-node-status"
description = "API implementation and types for querying a nodes status."
version = "1.0.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
exclude.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
nix = { workspace = true, optional = true }
openssl = { workspace = true, optional = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json.workspace = true
tokio = { workspace = true, optional = true }

proxmox-router = { workspace = true, optional = true }
proxmox-schema = { workspace = true, features = [ "api-macro", "api-types" ] }
proxmox-sys = { workspace = true, optional = true }

[features]
default = []
api = [
    "dep:anyhow",
    "dep:hex",
    "dep:nix",
    "dep:openssl",
    "dep:proxmox-router",
    "dep:proxmox-sys",
    "dep:tokio"
]
