overlay = "."
crate_src_path = ".."

[source]
# TODO: update once public
vcs_git = ""
vcs_browser = ""
maintainer = "Proxmox Support Team <support@proxmox.com>"

[packages.lib]
depends = [ "uuid-dev" ]
