[package]
name = "proxmox-simple-config"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
exclude.workspace = true
description = "Simple key/value format for configuration files."

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
log = { workspace = true, optional = true }

proxmox-schema = { workspace = true, features = ["api-macro", "api-types"] }
